ALTER TABLE `disponibilidade`.`alarmes` 
DROP PRIMARY KEY,
ADD PRIMARY KEY (`logId`, `site`, `eventTime`)  COMMENT '';

ALTER TABLE `disponibilidade`.`alarmes` PARTITION BY RANGE ( YEAR(eventTime) ) (
    PARTITION p2012 VALUES LESS THAN (2013),
    PARTITION p2013 VALUES LESS THAN (2014),
    PARTITION p2014 VALUES LESS THAN (2015),
    PARTITION p2015 VALUES LESS THAN (2016),
    PARTITION p2016 VALUES LESS THAN (2017),
    PARTITION pOTHERS VALUES LESS THAN MAXVALUE
);

ALTER TABLE `disponibilidade`.`alarmes` 
ENGINE = InnoDB ;

ALTER TABLE `disponibilidade`.`alarmes` 
DROP INDEX `LAST_UPDATE` ,
DROP INDEX `INDEX_EVENTTIME` ,
DROP INDEX `CLOSE_INDEX` ;
